name: gaze_interactive
description: Gaze Interaction implements the interaction of eye-trackers (or pointer other devices) with specifically designed gaze interactive widgets.
version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  # For Linux you need to do the following:
  # https://github.com/bluefireteam/audioplayers/blob/main/packages/audioplayers_linux/requirements.md
  audioplayers: ^6.0.0
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.3.5
  intl: ^0.19.0
  logger: ^2.4.0
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.3.1
  flutter_shake_animated: ^0.0.5
  speech_to_text: ^7.0.0
  pulsator: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  riverpod_generator: ^2.4.2
  json_serializable: ^6.8.0

flutter:
  assets:
    - lib/assets/
    - lib/assets/click.mp3
    - lib/assets/space_click.m4a
